[package]
name = "rust_reddit_browser"
version = "0.1.0"
authors = ["Romain Guillebert <romain.guillebert@deliveroo.co.uk>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
serde = "*"
serde_derive = "*"
serde_json = "*"
term_size = "0.3.1"
termios = "0.3.1"
